"""users table

Revision ID: a26aeb6be358
Revises: 
Create Date: 2019-12-02 17:37:27.873948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26aeb6be358'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('countries_ibfk_1', 'countries', type_='foreignkey')
    op.create_foreign_key('countries_ibfk_1', 'countries', 'category_country', ['category_id'], ['id'], source_schema='skiresorts', referent_schema='skiresorts')
    op.drop_constraint('skiresorts_main_ibfk_2', 'skiresorts_main', type_='foreignkey')
    op.drop_constraint('skiresorts_main_ibfk_1', 'skiresorts_main', type_='foreignkey')
    op.create_foreign_key('skiresorts_main_ibfk_2', 'skiresorts_main', 'countries', ['country_category'], ['id'], source_schema='skiresorts', referent_schema='skiresorts')
    op.create_foreign_key('skiresorts_main_ibfk_1', 'skiresorts_main', 'currency_type', ['currency'], ['id'], source_schema='skiresorts', referent_schema='skiresorts')
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'skiresorts_main', ['fav_resort'], ['id'], source_schema='skiresorts', referent_schema='skiresorts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_1', 'users', schema='skiresorts', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'skiresorts_main', ['fav_resort'], ['id'])
    op.drop_constraint('skiresorts_main_ibfk_1', 'skiresorts_main', schema='skiresorts', type_='foreignkey')
    op.drop_constraint('skiresorts_main_ibfk_2', 'skiresorts_main', schema='skiresorts', type_='foreignkey')
    op.create_foreign_key('skiresorts_main_ibfk_1', 'skiresorts_main', 'currency_type', ['currency'], ['id'])
    op.create_foreign_key('skiresorts_main_ibfk_2', 'skiresorts_main', 'countries', ['country_category'], ['id'])
    op.drop_constraint('countries_ibfk_1', 'countries', schema='skiresorts', type_='foreignkey')
    op.create_foreign_key('countries_ibfk_1', 'countries', 'category_country', ['category_id'], ['id'])
    # ### end Alembic commands ###
