"""skres table

Revision ID: ae04351b0bc3
Revises: a26aeb6be358
Create Date: 2019-12-03 17:23:30.397826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae04351b0bc3'
down_revision = 'a26aeb6be358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', mysql.VARCHAR(collation='utf8_unicode_ci', length=32), nullable=False),
    sa.PrimaryKeyConstraint('version_num'),
    schema='skiresorts',
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_constraint('countries_ibfk_1', 'countries', type_='foreignkey')
    op.create_foreign_key('countries_ibfk_1', 'countries', 'category_country', ['category_id'], ['id'], source_schema='skiresorts', referent_schema='skiresorts')
    op.drop_constraint('skiresorts_main_ibfk_1', 'skiresorts_main', type_='foreignkey')
    op.drop_constraint('skiresorts_main_ibfk_2', 'skiresorts_main', type_='foreignkey')
    op.create_foreign_key('skiresorts_main_ibfk_1', 'skiresorts_main', 'currency_type', ['currency'], ['id'], source_schema='skiresorts', referent_schema='skiresorts')
    op.create_foreign_key('skiresorts_main_ibfk_2', 'skiresorts_main', 'countries', ['country_category'], ['id'], source_schema='skiresorts', referent_schema='skiresorts')
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'skiresorts_main', ['fav_resort'], ['id'], source_schema='skiresorts', referent_schema='skiresorts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_1', 'users', schema='skiresorts', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'skiresorts_main', ['fav_resort'], ['id'])
    op.drop_constraint('skiresorts_main_ibfk_2', 'skiresorts_main', schema='skiresorts', type_='foreignkey')
    op.drop_constraint('skiresorts_main_ibfk_1', 'skiresorts_main', schema='skiresorts', type_='foreignkey')
    op.create_foreign_key('skiresorts_main_ibfk_2', 'skiresorts_main', 'countries', ['country_category'], ['id'])
    op.create_foreign_key('skiresorts_main_ibfk_1', 'skiresorts_main', 'currency_type', ['currency'], ['id'])
    op.drop_constraint('countries_ibfk_1', 'countries', schema='skiresorts', type_='foreignkey')
    op.create_foreign_key('countries_ibfk_1', 'countries', 'category_country', ['category_id'], ['id'])
    op.drop_table('alembic_version', schema='skiresorts')
    # ### end Alembic commands ###
